src/Entity/Chene/JeuEnChene.php
<?php

namespace App\Entity\Chene;

use App\Entity\General\Conversation;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Chene\JeuEnCheneRepository")
 * @UniqueEntity("nom")
 * @Vich\Uploadable
 */
class JeuEnChene {

    const codeLocation = [
                0 => 'une semaine',
                1 => 'deux semaines',
                2 => 'un mois'
    ];
    
    const codeNiveauDifficulte = [
                0 => 'facile',
                1 => 'moyen',
                2 => 'difficile'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $disponible = false;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" : 5})
     * @assert\Range(min=0, max=10)
     */
    private $difficulteObservation = 5;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" : 5})
     * @assert\Range(min=0, max=10)
     */
    private $difficulteRaisonnement = 5;

    /**
     * @ORM\Column(type="integer")
     */
    private $niveauDifficulte;
    
    /**
     * @ORM\Column(type="integer")
     */
    private $tempsLocation;
    
    /**
     * @ORM\Column(type="integer", options={"default" : 1})
     */
    private $prix = 1;

    /**
     * @ORM\ManyToMany(targetEntity="\App\Entity\Chene\Babiole", inversedBy="jeuEnChenes", cascade={"persist"})
     * @var ArrayCollection<Babiole> 
     */
    private $babioles;

    /**
     * @Vich\UploadableField(mapping="jeu_en_chene_image", fileNameProperty="imageName")     
     * @assert\Image(mimeTypes="image/jpeg") 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @param \DateTimeInterface
     */
    private $majDate;

    /**
     * @ORM\Column(type="integer", options={"default" : 1})
     */
    private $num = 1;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" : 1})
     */
    private $nombreEtapes = 1;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Chene\CollectionChene", inversedBy="jeuEnChenes")
     * @var CollectionChene     
     */
    private $collectionChene;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Chene\ReservationJeu", mappedBy="jeu", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\General\Conversation", mappedBy="lienJeuEnChene")
     */
    private $conversations;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $construit = false;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleur;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentairesGourou;


    public function __construct() {
        $this->babioles = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->conversations = new ArrayCollection();
    }

    /**
     * 
     * @return int|null
     */
    public function getId(): ?int {
        return $this->id;
    }
    
    
    /**
     * 
     * @return string|null
     */
    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    /**
     * 
     * @param string|null $couleur
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function setCouleur(?string $couleur): JeuEnChene
    {
        $this->couleur = $couleur;

        return $this;
    }

    /**
     * 
     * @return string|null
     */
    public function getNom(): ?string {
        return $this->nom;
    }

    /**
     * 
     * @return string|null
     */
    public function getNomEtCollection(): ?string {
        if ($this->collectionChene) {
            return $this->nom . " [" . $this->collectionChene->getNom() . "]";
        } else {
            return $this->nom;
        }
    }

    /**
     * 
     * @param string $nom
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function setNom(string $nom): JeuEnChene {
        $this->nom = $nom;

        return $this;
    }

    /**
     * 
     * @return string
     */
    public function getSlug(): string {
        return ( new Slugify())->slugify($this->nom);
    }

    /**
     * 
     * @return string|null
     */
    public function getDescription(): ?string {
        return $this->description;
    }

    /**
     * 
     * @param string|null $description
     * @return \App\Entity\Chene\JeuEnChene 
     */
    public function setDescription(?string $description): JeuEnChene {
        $this->description = $description;

        return $this;
    }

    /**
     * 
     * @return bool|null
     */
    public function getDisponible(): ?bool {
        return $this->disponible;
    }

    /**
     * 
     * @param bool $disponible
     * @return JeuEnChene
     */
    public function setDisponible(bool $disponible): JeuEnChene {
        $this->disponible = $disponible;

        return $this;
    }

    /**
     * 
     * @return int|null
     */
    public function getDifficulteObservation(): ?int {
        return $this->difficulteObservation;
    }

    /**
     * 
     * @param int|null $difficulteObservation
     * @return JeuEnChene
     */
    public function setDifficulteObservation(?int $difficulteObservation): JeuEnChene {
        $this->difficulteObservation = $difficulteObservation;

        return $this;
    }

    /**
     * 
     * @return int|null 
     */
    public function getDifficulteRaisonnement(): ?int {
        return $this->difficulteRaisonnement;
    }

    /**
     * 
     * @param int|null $difficulteRaisonnement
     * @return JeuEnChene
     */
    public function setDifficulteRaisonnement(?int $difficulteRaisonnement): JeuEnChene {
        $this->difficulteRaisonnement = $difficulteRaisonnement;

        return $this;
    }

    /**
     * 
     * @return int|null
     */
    public function getTempsLocation(): ?int {
        return $this->tempsLocation;
    }

    /**
     * @return string
     */
    public function getTempsLocationString(): string {
        return self::codeLocation[$this->tempsLocation];
    }

    /**
     * 
     * @param int $tempsLocation
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function setTempsLocation(int $tempsLocation): JeuEnChene {
        $this->tempsLocation = $tempsLocation;

        return $this;
    }      
    
    /**
     * 
     * @return int|null
     */
    public function getNiveauDifficulte(): ?int {
        return $this->niveauDifficulte;
    }

    /**
     * @return string
     */
    public function getNiveauDifficulteString(): string {
        return self::codeNiveauDifficulte[$this->niveauDifficulte];
    }

    /**
     * 
     * @param int $niveauDifficulte
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function setNiveauDifficulte(int $niveauDifficulte): JeuEnChene {
        $this->niveauDifficulte = $niveauDifficulte;

        return $this;
    }

    /**
     * 
     * @return int|null
     */
    public function getPrix(): ?int {
        return $this->prix;
    }

    /**
     * 
     * @return string
     */
    public function getPrixFormate(): string {
        if ($this->prix > 1)
            return $this->prix . " babioles";
        else
            return $this->prix . " babiole";
    }

    /**
     * 
     * @param int $prix
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function setPrix(int $prix): JeuEnChene {
        $this->prix = $prix;

        return $this;
    }

    /**
     * @return Babiole[]
     */
    public function getBabioles(): Collection {
        return $this->babioles;
    }

    /**
     * 
     * @param Babiole $babiole
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function addBabiole(Babiole $babiole): JeuEnChene {
        if (!$this->babioles->contains($babiole)) {
            $this->babioles[] = $babiole;
        }

        return $this;
    }

    /**
     * 
     * @param Babiole $babiole
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function removeBabiole(Babiole $babiole): JeuEnChene {
        if ($this->babioles->contains($babiole)) {
            $this->babioles->removeElement($babiole);
        }

        return $this;
    }

    /**
     * 
     * @return \DateTimeInterface|null
     */
    public function getMajDate(): ?\DateTimeInterface {
        return $this->majDate;
    }

    /**
     * 
     * @param \DateTimeInterface $majDate
     * @return \App\Entity\Chene\JeuEnChene
     */
    public function setMajDate(\DateTimeInterface $majDate): JeuEnChene {
        $this->majDate = $majDate;

        return $this;
    }

    /**
     * 
     * @return int|null
     */
    public function getNum(): ?int {
        return $this->num;
    }

    /**
     * 
     * @param int $num
     * @return \self
     */
    public function setNum(int $num): self {
        $this->num = $num;

        return $this;
    }

    /**
     * 
     * @return int|null
     */
    public function getNombreEtapes(): ?int {
        return $this->nombreEtapes;
    }

    /**
     * 

src/Form/Chene/BabioleRechercheType.php
<?php

namespace App\Form\Chene;

use App\Entity\Chene\BabioleRecherche;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BabioleRechercheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('maxValeur', IntegerType::class, [
                'required' => false,
                'label' => false,
                'attr' => [
                    'placeholder' => 'Valeur maximale',
                    'min' => 0
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => BabioleRecherche::class,
            'method' => 'get',
            'csrf_protection' => false
        ]);
    }
    
    public function getBlockPrefix() 
    {
        return '';
    }
}

src/Form/Chene/BabioleType.php
<?php

namespace App\Form\Chene;

use App\Entity\Chene\Babiole;
use App\Entity\Chene\CategorieBabiole;
use App\Repository\Chene\CategorieBabioleRepository;
use App\Entity\General\User;
use App\Repository\General\UserRepository;
use App\Entity\Chene\TypeBabiole;
use App\Repository\Chene\TypeBabioleRepository;
use App\Entity\Chene\ReservationJeu;
use App\Repository\Chene\ReservationJeuRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BabioleType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('nom')
                ->add('valeur', IntegerType::class, [
                    'attr' => [
                        'min' => 0
                    ]
                ])
                ->add('typeBabiole', EntityType::class, [
                    'class' => TypeBabiole::class,
                    'placeholder' => 'Non défini',
                    'choice_label' => 'nom',
                    'query_builder' => function (TypeBabioleRepository $er) {
                        return $er->createQueryBuilder('b')
                                ->orderBy('b.nom', 'ASC');
                    }
                ])
                ->add('imageFile', FileType::class, [
                    'required' => false
                ])
                ->add('categorieBabiole', EntityType::class, [
                    'class' => CategorieBabiole::class,
                    'placeholder' => 'Non défini',
                    'choice_label' => 'nom',
                    'query_builder' => function (CategorieBabioleRepository $er) {
                        return $er->createQueryBuilder('b')
                                ->orderBy('b.nom', 'ASC');
                    }
                ])
                ->add('user', EntityType::class, [
                    'class' => User::class,
                    'choice_label' => 'username',
                    'placeholder' => 'Aucun',
                    'label' => "Joueur l'ayant offert",
                    'query_builder' => function (UserRepository $er) {
                        return $er->createQueryBuilder('b')
                                ->orderBy('b.username', 'ASC');
                    },
                    'required' => false
                ])
                ->add('commentaireGourou', TextareaType::class, [
                    'required' => false
                        ]
                )
                ->add('description')
                ->add('ReservationJeu', EntityType::class, [
                    'class' => ReservationJeu::class,
                'placeholder' => 'Aucune référence',
                'choice_label' => function ($reservation) {
                                    return $reservation->getIntitule();
                                    },
                'query_builder' => function (ReservationJeuRepository $er ) {
                        return $er->createQueryBuilder('r')
                            ->Join('r.user', 'user')
                            ->orderBy('r.dateDemande', 'DESC');
                    },                            
                'required' => false
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Babiole::class,
            'translation_domain' => 'forms'
        ]);
    }

}

src/Form/Chene/CategorieBabioleType.php
<?php

namespace App\Form\Chene;

use App\Entity\Chene\CategorieBabiole;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieBabioleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('num', IntegerType::class, [
               'attr' => [
                   'min' => 1
                ]
            ])
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CategorieBabiole::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Form/Chene/CollectionCheneType.php
<?php

namespace App\Form\Chene;

use App\Entity\Chene\CollectionChene;
use App\Entity\Chene\JeuEnChene;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class CollectionCheneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('num', IntegerType::class, [
               'attr' => [
                   'min' => 1
                ]
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])    
            ->add('description')    
            ->add('enigme')            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CollectionChene::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Form/Chene/CreateRetourFlow.php
<?php

namespace App\Form\Chene;

use Craue\FormFlowBundle\Form\FormFlow;
use Craue\FormFlowBundle\Form\FormFlowInterface;
use App\Form\Chene\CreateRetourForm;

class CreateRetourFlow extends FormFlow {

    public function invalidateStepData($fromStepNumber) {
        // do nothing, this prevents us from deleting step data when user hits "back" button
    }

    protected function loadStepsConfig() {
        return [
            [
                'label' => 'Lieu de retour',
                'form_type' => CreateRetourForm::class,
            ],
            [
                'label' => 'Date de retour',
                'form_type' => CreateRetourForm::class
            ]
        ];
    }

}

templates/chene/jeuEnChene/_avis.html.twig
<div class="card mb-4 border-dark card-avis border-secondary w-100">
    <div class="card-header">
        {% if reservation.note == -1 %}
            Avis sans note
        {% else %}    
            {%  include 'outils/_rating.html.twig' with {'valeur': reservation.note } %}
        {% endif%}

        <div class="mt-2">
            Publié par 
            {% if reservation.user.masque %}
                <b>un joueur anonyme</b>
            {% else %}
                <b>{{ reservation.user.getGradeString("Chêne") }} {{ reservation.user.getUSername }}</b>
            {% endif %}
            le {{ reservation.dateDemande | format_datetime('long', 'none', locale='fr')}}
        </div>

    </div>
    <div class="card-body">
        {{ reservation.avisPublic }}
    </div>

</div>

templates/chene/jeuEnChene/_jeuEnChene.html.twig
{#{% cache 'jeuEnChene' ~ jeuEnChene.id  jeuEnChene.majDate.timestamp|default(2019) %}#}
<div class="card mb-4 border-dark rounded_card jeu-card">
    {% if jeuEnChene.imageName %}
        <img class="card-img-top rounded_card" src="{{ vich_uploader_asset(jeuEnChene, 'imageFile') | imagine_filter("my_thumb") }}" > 
    {% else %}
        <img class="card-img-top rounded_card" src="{{ 'images/jeuEnChene/vide.jpg' | imagine_filter("my_thumb") }}" > 
    {% endif%}

    {% if jeuEnChene.disponible %}
        <img class="img-over" src="{{ asset('images/base/disponible.png') }}" > 
    {% else %}            
        <img class="img-over" src="{{ asset('images/base/non_disponible.png') }}" > 
    {% endif %}

    <div class="card-body pt-2 pb-0 d-flex flex-column">
        <h3 class="">
            {% if sansLien is defined %}
                {{ jeuEnChene.nom }}
            {% else %}  
                <a class="stretched-link d-inline text-dark" href="{{ path("jeuEnChene.show", { slug: jeuEnChene.slug, id: jeuEnChene.id }) }}">
                    {{ jeuEnChene.nom }}
                </a>  
            {% endif %}  
            {% if is_granted('ROLE_USER') or is_granted('ROLE_ADMIN') %}
                {% if app.user.aReussiJeu( jeuEnChene ) %}                    
                    <div class="jeu-reussi d-inline float-right font-weight-bold text-success rounded-circle bg-white pl-1 pr-1" style="border-color:{{jeuEnChene.couleur}};"><span class="fas fa-check text-success border-circle" aria-hidden="true"></span></div>                
                {% endif %}
            {% endif %}            
        </h3>

        <div class="font-italic font-weight-bold">{{ jeuEnChene.description|nl2br(false) }}</div>   

        <div style="margin-top: auto;">
            <hr class="mt-2 mb-2" style="heigth:10px;">

            <div class="font-caracteristique">
                <div class="font-weight-bold d-inline">
                    Collection : 
                </div>
                <div class="d-inline">
                    {{ jeuEnChene.collectionChene.nom }} - jeu {{ jeuEnChene.num }}
                </div>
            </div>

            <div class="font-caracteristique">
                <div class="font-weight-bold d-inline">
                    Durée de location conseillé : 
                </div>
                <div class="d-inline">
                    {{ jeuEnChene.getTempsLocationString }}
                </div>
            </div> 

            <div class="font-caracteristique">
                <div class="font-weight-bold d-inline">
                    Niveau :
                </div>
                <div class="d-inline">
                    {{ jeuEnChene.niveauDifficulteString }}
                </div>
            </div>
                
            <div class="font-caracteristique">
                <div class="font-weight-bold d-inline">
                    Difficulté de réflexion :
                </div>
                <div class="d-inline">
                    {% if jeuEnChene.difficulteRaisonnement %}{{ jeuEnChene.difficulteRaisonnement }}{% else %}?{% endif %} / 10
                </div>
            </div> 

            <div class="font-caracteristique">
                <div class="font-weight-bold d-inline">
                    Difficulté d'observation :
                </div>
                <div class="d-inline">
                    {% if jeuEnChene.difficulteObservation %}{{ jeuEnChene.difficulteObservation }}{% else %}?{% endif %} / 10
                </div>
            </div> 

            <div class="font-caracteristique">
                <div class="font-weight-bold d-inline">
                    Nombre d'étapes :
                </div>
                <div class="d-inline">
                    {% if jeuEnChene.nombreEtapes %}{{ jeuEnChene.nombreEtapes }}{% else %}?{% endif %}
                </div>
            </div>
        </div>
    </div> 

    {% if is_granted('ROLE_USER') %}
        {% if jeuEnChene.estGratuit( app.user.id ) %}
            <div class="{% if jeuEnChene.disponible %}footer-disponible{% else %}footer-non-disponible{% endif %} bg-warning  text-center mt-2 mb-0"">
                <div>
                    Créé avec une de vos babioles 
                </div>
                <h5 class="mb-0">
                    GRATUIT POUR VOUS !
                </h5>
            </div>
        {% else %}
            <h4 class="{% if jeuEnChene.disponible %}footer-disponible{% else %}footer-non-disponible{% endif %} bg-gris  text-center mt-2 mb-0">
                Prix conseillé : {{ jeuEnChene.prixFormate }}
            </h4>
        {% endif%}
    {% else %}
        <h4 class="{% if jeuEnChene.disponible %}footer-disponible{% else %}footer-non-disponible{% endif %} bg-gris  text-center mt-2 mb-0">
            Prix conseillé : {{ jeuEnChene.prixFormate }}
        </h4>
    {% endif%}


</div>
{#{% endcache %}#}

templates/chene/jeuEnChene/index.html.twig
{% extends "chene/baseChene.html.twig" %}

{% block body %}
    <div class="jumbotron mon-jumbotron">
        <div class="container">
            <h1 class="text-center mb-0">
                {% if filtre %}
                    {% if nb_jeux_en_chene == 0 %}
                        Aucun Jeu en Chêne ne correspond à votre recherche
                    {% elseif nb_jeux_en_chene == 1 %}
                        Un seul Jeu en Chêne correspond à votre recherche
                    {% else %}
                        {{nb_jeux_en_chene}} Jeux en Chêne correspondent à votre recherche
                    {% endif %}
                {% else %}
                    Il existe actuellement {{nb_jeux_en_chene}} Jeux en Chêne
                {% endif%}
             {% if not filtre %}
                <p class="text-right no-margin float-right">
                    <a class="btn btn-secondary align-right no-marging" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Options de recherche</a>
                </p>
            {% endif %}
            </h1>
            <div class="collapse {% if filtre %}show{% endif %}" id="multiCollapseExample1">
                <hr class="mb-2 mt-2">
                {{ form_start(form) }}

                <div class="form-row">
                    <div class="col-md-3 no-margin ">
                        <div class="input-group mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Seulement les disponibles</span>
                            </div>  
                            <div class="pt-2 custom-control-lg-form custom-control custom-checkbox">
                                {{ form_widget(form.disponible) }}
                            </div>
                        </div>
                    </div> 

                    <div class="col-md-4 no-margin">
                        <div class="input-group mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Difficulté de raisonnement</span>
                            </div>
                            {{ form_widget(form.minDifficulteRaisonnement) }}
                            {{ form_widget(form.maxDifficulteRaisonnement) }}
                        </div>
                    </div>

                    <div class="col-md-3 no-margin">
                        <div class="input-group  mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Prix</span>
                            </div>
                            {{ form_widget(form.minPrix) }}
                            {{ form_widget(form.maxPrix) }}
                        </div>
                    </div>
                    <div class="col-md-2 no-margin">
                        <div class="input-group  mb-1">
                            {{ form_widget(form.collection) }}
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-3 no-margin">
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="input-group  mb-1">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Niveau de difficulté</span>
                                    </div>
                                    {{ form_widget(form.niveauDifficulte) }}
                                </div>
                            </div>
                        </div>
                    </div>    

                    <div class="col-md-4 no-margin">
                        <div class="input-group mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Difficulté d'observation</span>
                            </div>
                            {{ form_widget(form.minDifficulteObservation) }}
                            {{ form_widget(form.maxDifficulteObservation) }}
                        </div>
                    </div>

                    <div class="col-md-3 no-margin">
                        <div class="input-group mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Nb. d'étapes</span>
                            </div>
                            {{ form_widget(form.minEtape) }}
                            {{ form_widget(form.maxEtape) }}
                        </div>
                    </div>

                    <div class="col-md-2 text-right">
                        <div class="no-margin">
                            {{ form_widget(form.recherche) }}
                        </div>
                    </div>

                </div>
                {{ form_end(form) }}

            </div>
        </div>
    </div>

    {{ include('outils/_flash.html.twig') }}   

    <div class="container mt-4 ">
        <div class="row mt-4">
            {% for jeuEnChene in jeux_en_chene  %}
                <div class="d-flex align-items-stretch col-md-4">
                    {%  include 'chene/jeuEnChene/_jeuEnChene.html.twig' %}
                </div>
            {% endfor %}
        </div>

        {# display navigation #}
        <div class="pagination">
            {{ knp_pagination_render(jeux_en_chene) }}
        </div>
    </div>
{% endblock body %}